### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by h0adp0re** [yaegassy/coc-vitest#1]
Thanks for this plugin, it's already useful as it is. However, I'm used to watching for changes as I'm writing tests. Could this be implemented in this project?

**Comment by yaegassy** [comment]
`coc-vitest` is a coc-extension created for quick execution of the `vitest run` command. When I use watch mode, I run vitest with cli in a separate shell, e.g. tmux.

I'm not thinking about adding "watch mode" feature in `coc-vitest` at this time, but will consider it when we have more time.

**Comment by h0adp0re** [comment]
Now that I think about it, you're right. I will just run watch mode in a split. You can close this if you want, thanks!

**Comment by schontz** [comment]
I still think this is a valuable option, especially with current file or single test mode. I created a PR if you care to merge it.

**Comment by yaegassy** [comment]
schontz's PR has been merged.
